# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.srcs/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0.xci
# IP: The module: 'kria_starter_kit_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.srcs/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0.xci
# IP: The module: 'kria_starter_kit_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ASUS/iCloudDrive/PhD-kriask/prj/blink_mk_III/blink_mk_III.gen/sources_1/bd/kria_starter_kit/ip/kria_starter_kit_clk_wiz_0_0/kria_starter_kit_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_starter_kit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
