# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# Block Designs: bd/kria_starter_kit/kria_starter_kit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit || ORIG_REF_NAME==kria_starter_kit} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_xlslice_0_0/kria_starter_kit_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_xlslice_0_0 || ORIG_REF_NAME==kria_starter_kit_xlslice_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_zynq_ultra_ps_e_0_0/kria_starter_kit_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_rst_ps8_0_99M_0/kria_starter_kit_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_rst_ps8_0_99M_0 || ORIG_REF_NAME==kria_starter_kit_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_axi_cfg_register_0_0/kria_starter_kit_axi_cfg_register_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_axi_cfg_register_0_0 || ORIG_REF_NAME==kria_starter_kit_axi_cfg_register_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_xbar_0/kria_starter_kit_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_xbar_0 || ORIG_REF_NAME==kria_starter_kit_xbar_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_auto_ds_0/kria_starter_kit_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_auto_ds_0 || ORIG_REF_NAME==kria_starter_kit_auto_ds_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_auto_pc_0/kria_starter_kit_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_auto_pc_0 || ORIG_REF_NAME==kria_starter_kit_auto_pc_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_ps8_0_axi_periph_0/kria_starter_kit_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_ps8_0_axi_periph_0 || ORIG_REF_NAME==kria_starter_kit_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_axi_cfg_register_0_1/kria_starter_kit_axi_cfg_register_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_axi_cfg_register_0_1 || ORIG_REF_NAME==kria_starter_kit_axi_cfg_register_0_1} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_axi_cfg_register_1_0/kria_starter_kit_axi_cfg_register_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_axi_cfg_register_1_0 || ORIG_REF_NAME==kria_starter_kit_axi_cfg_register_1_0} -quiet] -quiet

# XDC: c:/Users/ASUS/Documents/PhD/kriask/prj/fan_ex/fan_ex.gen/sources_1/bd/kria_starter_kit/kria_starter_kit_ooc.xdc
