set_property SRC_FILE_INFO {cfile:C:/Users/bevilacqua/Documents/projects/KRIA-SK/code/nand_ps_mk_III/nand_ps_mk_III.srcs/constrs_1/imports/xdc/default.xdc rfile:../../../nand_ps_mk_III.srcs/constrs_1/imports/xdc/default.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {fan_en_b}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {uf1}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA12 [get_ports {rpi_16}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {rpi_18}]
