/include/ "system-conf.dtsi"
/ {
        amba_pl: amba_pl {
                compatible = "simple-bus";
                ranges ;
                axi_cfg_register_0: axi_cfg_register@b0000000 {
                        clock-names = "aclk";
                        clocks = <&zynqmp_clk 71>;
                        compatible = "xlnx,axi-cfg-register-1.0";
                        reg = <0x0 0xb0000000 0x0 0x80>;
                };
                afi0: afi0 {
                        compatible = "xlnx,afi-fpga";
                        config-afi = < 0 0>, <1 0>, <2 0>, <3 0>, <4 0>, <5 0>, <6 0>, <7 0>, <8 0>, <9 0>, <10 0>, <11 0>, <12 0>, <13 0>, <14 0xa00>, <15 0x000>;
                };
                clocking0: clocking0 {
                        #clock-cells = <0>;
                        assigned-clock-rates = <99999001>;
                        assigned-clocks = <&zynqmp_clk 71>;
                        clock-output-names = "fabric_clk";
                        clocks = <&zynqmp_clk 71>;
                        compatible = "xlnx,fclk";
                };
                clocking1: clocking1 {
                        #clock-cells = <0>;
                        assigned-clock-rates = <99999001>;
                        assigned-clocks = <&zynqmp_clk 72>;
                        clock-output-names = "fabric_clk";
                        clocks = <&zynqmp_clk 72>;
                        compatible = "xlnx,fclk";
                };
                fifo_in: axi_fifo_mm_s@a0010000 {
                        clock-names = "s_axi_aclk";
                        clocks = <&zynqmp_clk 71>;
                        compatible = "xlnx,axi-fifo-mm-s-4.3";
                        reg = <0x0 0xa0010000 0x0 0x10000>;
                        xlnx,axi-str-rxd-protocol = "XIL_AXI_STREAM_ETH_DATA";
                        xlnx,axi-str-rxd-tdata-width = <0x20>;
                        xlnx,axi-str-txc-protocol = "XIL_AXI_STREAM_ETH_CTRL";
                        xlnx,axi-str-txc-tdata-width = <0x20>;
                        xlnx,axi-str-txd-protocol = "XIL_AXI_STREAM_ETH_DATA";
                        xlnx,axi-str-txd-tdata-width = <0x20>;
                        xlnx,axis-tdest-width = <0x4>;
                        xlnx,axis-tid-width = <0x4>;
                        xlnx,axis-tuser-width = <0x4>;
                        xlnx,data-interface-type = <0x0>;
                        xlnx,has-axis-tdest = <0x0>;
                        xlnx,has-axis-tid = <0x0>;
                        xlnx,has-axis-tkeep = <0x0>;
                        xlnx,has-axis-tstrb = <0x0>;
                        xlnx,has-axis-tuser = <0x0>;
                        xlnx,rx-cascade-height = <0x0>;
                        xlnx,rx-enable-ecc = <0x0>;
                        xlnx,rx-fifo-depth = <0x800>;
                        xlnx,rx-fifo-pe-threshold = <0x5>;
                        xlnx,rx-fifo-pf-threshold = <0x1fb>;
                        xlnx,rx-has-ecc-err-inject = <0x0>;
                        xlnx,s-axi-id-width = <0x4>;
                        xlnx,s-axi4-data-width = <0x20>;
                        xlnx,select-xpm = <0x0>;
                        xlnx,tx-cascade-height = <0x0>;
                        xlnx,tx-enable-ecc = <0x0>;
                        xlnx,tx-fifo-depth = <0x200>;
                        xlnx,tx-fifo-pe-threshold = <0x5>;
                        xlnx,tx-fifo-pf-threshold = <0x1fb>;
                        xlnx,tx-has-ecc-err-inject = <0x0>;
                        xlnx,use-rx-cut-through = <0x0>;
                        xlnx,use-rx-data = <0x1>;
                        xlnx,use-tx-ctrl = <0x0>;
                        xlnx,use-tx-cut-through = <0x0>;
                        xlnx,use-tx-data = <0x0>;
                };
                fifo_out: axi_fifo_mm_s@a0000000 {
                        clock-names = "s_axi_aclk";
                        clocks = <&zynqmp_clk 71>;
                        compatible = "xlnx,axi-fifo-mm-s-4.3";
                        reg = <0x0 0xa0000000 0x0 0x10000>;
                        xlnx,axi-str-rxd-protocol = "XIL_AXI_STREAM_ETH_DATA";
                        xlnx,axi-str-rxd-tdata-width = <0x20>;
                        xlnx,axi-str-txc-protocol = "XIL_AXI_STREAM_ETH_CTRL";
                        xlnx,axi-str-txc-tdata-width = <0x20>;
                        xlnx,axi-str-txd-protocol = "XIL_AXI_STREAM_ETH_DATA";
                        xlnx,axi-str-txd-tdata-width = <0x20>;
                        xlnx,axis-tdest-width = <0x4>;
                        xlnx,axis-tid-width = <0x4>;
                        xlnx,axis-tuser-width = <0x4>;
                        xlnx,data-interface-type = <0x0>;
                        xlnx,has-axis-tdest = <0x0>;
                        xlnx,has-axis-tid = <0x0>;
                        xlnx,has-axis-tkeep = <0x0>;
                        xlnx,has-axis-tstrb = <0x0>;
                        xlnx,has-axis-tuser = <0x0>;
                        xlnx,rx-cascade-height = <0x0>;
                        xlnx,rx-enable-ecc = <0x0>;
                        xlnx,rx-fifo-depth = <0x200>;
                        xlnx,rx-fifo-pe-threshold = <0x5>;
                        xlnx,rx-fifo-pf-threshold = <0x1fb>;
                        xlnx,rx-has-ecc-err-inject = <0x0>;
                        xlnx,s-axi-id-width = <0x4>;
                        xlnx,s-axi4-data-width = <0x20>;
                        xlnx,select-xpm = <0x0>;
                        xlnx,tx-cascade-height = <0x0>;
                        xlnx,tx-enable-ecc = <0x0>;
                        xlnx,tx-fifo-depth = <0x800>;
                        xlnx,tx-fifo-pe-threshold = <0x5>;
                        xlnx,tx-fifo-pf-threshold = <0x1fb>;
                        xlnx,tx-has-ecc-err-inject = <0x0>;
                        xlnx,use-rx-cut-through = <0x0>;
                        xlnx,use-rx-data = <0x0>;
                        xlnx,use-tx-ctrl = <0x1>;
                        xlnx,use-tx-cut-through = <0x0>;
                        xlnx,use-tx-data = <0x1>;
                };
        };
};