# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# Block Designs: bd/kria_starter_kit/kria_starter_kit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit || ORIG_REF_NAME==kria_starter_kit} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_xlslice_0_0/kria_starter_kit_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_xlslice_0_0 || ORIG_REF_NAME==kria_starter_kit_xlslice_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_zynq_ultra_ps_e_0_0/kria_starter_kit_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_ila_0_0/kria_starter_kit_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_ila_0_0 || ORIG_REF_NAME==kria_starter_kit_ila_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_nand_gate_0_0/kria_starter_kit_nand_gate_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_nand_gate_0_0 || ORIG_REF_NAME==kria_starter_kit_nand_gate_0_0} -quiet] -quiet

# XDC: c:/Users/bevilacqua/Documents/projects/KRIA-SK/code/nand_ps_mk_III/nand_ps_mk_III.gen/sources_1/bd/kria_starter_kit/kria_starter_kit_ooc.xdc
